### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected

### ISSUE THREAD

**Issue by skunkwerk** [lelechen63/ATVGnet#4]
Hi Lele,

This may be an environment issue with my machine, but I'm unable to run the demo with a GPU virtual machine running Linux.  

Do I need to use CUDA 9, or will CUDA 10 work?

Thank you

This is the traceback:

$ python demo.py
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "demo.py", line 271, in <module>
    test()
  File "demo.py", line 173, in test
    pca = torch.FloatTensor( np.load('../basics/U_lrw1.npy')[:,:6]).cuda()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:74

This works fine though:
>> import torch
>> print(torch.cuda.device_count())
1

My nvidia-smi:
Sun May 26 05:32:33 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    74W / 149W |      0MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by skunkwerk** [comment]
Fixed by passing --device_ids 0 to the command line
