### ISSUE TITLE
local variable 'lmark' referenced before assignment

### ISSUE THREAD

**Issue by skunkwerk** [lelechen63/ATVGnet#5]
Am I doing something wrong?
Thanks

$ python demo.py --device_ids 0 --cuda CUDA --vg_model ../model
/generator_23.pth --at_model ../model/atnet_lstm_18.pth --lstm LSTM --p ../image/musk1_region.jpg -i ../audio/obama
.wav --sample_dir ../output

Traceback (most recent call last):
  File "demo.py", line 271, in <module>
    test()
  File "demo.py", line 192, in test
    example_image, example_landmark = generator_demo_example_lips( config.person)
  File "demo.py", line 164, in generator_demo_example_lips
    return dst, lmark
UnboundLocalError: local variable 'lmark' referenced before assignment

**Comment by skunkwerk** [comment]
solved by using image/musk1.jpg
